// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/2/2025, 11:28:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/samualdaugherty/design-portfolio-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/plugins/**/*.{js,ts,mjs}","/Users/samualdaugherty/design-portfolio-nuxt/composables/**/*.{js,ts,mjs}","/Users/samualdaugherty/design-portfolio-nuxt/utils/**/*.{js,ts,mjs}","/Users/samualdaugherty/design-portfolio-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/samualdaugherty/design-portfolio-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;